### PR TITLE
fix: change http client

### LINKED ISSUE #180: Http clients cause hot spots
### Describe this problem

Http client `io.holoinsight.server.home.alert.common.http.HttpProxy` may cause all requests to go to the same server.

### Steps to reproduce

Add ai alert rule, then in each computation cycle, the request traffic to the algorithm visits the same server.
 

### Expected behavior

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by masaimu**
# Which issue does this PR close?

Closes #180 

# What changes are included in this PR?

A new connection is established with each request.

# Are there any user-facing changes?

None.

# How does this change test

Local test.

### CODE REVIEW

File: server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java [hunk 1]
```diff
@@ -19,23 +26,69 @@ public class AlgorithmHttp {
...
+
   public static String invokeAlgorithm(String algorithmUrl, String requestBody) {
-    XHttpResponse respose = null;
+    Map<String, String> headers = new HashMap<>();
+    headers.put("Content-Type", "application/json");
+    return post(algorithmUrl, requestBody, headers);
+  }
+
+  public static String post(String algorithmUrl, String requestBody, Map<String, String> headers) {
+    CloseableHttpClient httpClient = HttpClients.createDefault();
```
Comment (xzchaoo) [inline server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java:43]: Must close httpClient in finally{}.

**Review by jsy1001de — APPROVED** [review]
LGTM
