### PR TITLE
fix(home): fix NPE in alert compute

### LINKED ISSUE #248: NPE in alert compute
## Describe this problem
Alert compute may occur NPE in alert notification.

## To Reproduce

```
2023-03-16 14:16:20,145 ERROR [alert-handler] i.h.s.h.a.s.c.AlertTaskCompute - [HoloinsightAlertInternalException][AlertTaskCompute][134] fail to execute alert task compute for null
java.lang.NullPointerException: null
        at io.holoinsight.server.home.alert.service.calculate.AlertTaskCompute.lambda$process$1(AlertTaskCompute.java:83) ~[home-alert-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_172]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_172]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_172]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_172]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_172]
        at io.holoinsight.server.home.alert.service.calculate.AlertTaskCompute.process(AlertTaskCompute.java:84) ~[home-alert-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at io.holoinsight.server.home.alert.service.task.AlertTaskScheduler.lambda$graphProcess$0(AlertTaskScheduler.java:103) ~[home-alert-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) ~[?:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627) ~[?:1.8.0_172]
        at java.lang.Thread.run(Thread.java:882) ~[?:1.8.0_172]
```

### PR DESCRIPTION
**Pull request by masaimu**
# Which issue does this PR close?

Closes #248 

# What changes are included in this PR?

- Fix potential NPE issue
- Comments in English

# Are there any user-facing changes?

None.

# How does this change test

Local test.

### CODE REVIEW

File: server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java [hunk 1]
```diff
@@ -153,7 +161,7 @@ private List<EventInfo> calculate(ComputeTaskPackage computeTaskPackage) {
       }
       latch.await();
     } catch (Exception e) {
-      LOGGER.error("AlarmTaskCompute Exception for {}", e.getMessage(), e);
+      LOGGER.error("AlertTaskCompute Exception for {}", e.getMessage(), e);
```
Comment (xzchaoo) [inline server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java:164]: e.getMessage() duplicated with e

**Review by xzchaoo — APPROVED** [review]
LGTM
